### ISSUE TITLE
A Stack Registry and CLI

### ISSUE THREAD

**Issue by prologic** [tutumcloud/stackfiles#43]
Are you guys planning on developing such a service and set f tools? I'd definitely like to get involved in something lie this. I find myself using `docker-compose.yml` (_I shorten it to just `dc.yml`_) and `docker-compose` a lot (_I shorten it to ``alias dc='docker-compose -f dc.yml`_).

It _would_ be really nice if we:
- Build a Stack registry service that users can publish, pull and deploy whole pre-built stacks.
- A CLI tool to easily manage this; e.g: `docker stack` or `stack`? (_Docker is pluggable now right?_).
- Be compatible with both Tutum `Stackfile`(s) and `docker-compose.yml`.

**Comment by MaximeHeckel** [comment]
Hi @prologic 

That's exactly what we are building and it will be released pretty soon although we didn't think yet about a CLI tool (but it could be a nice idea for a v2 indeed). Apart from that everything you asked will be available.

**Comment by prologic** [comment]
:+1:
