### ISSUE TITLE
Add download link of stackfiles

### ISSUE THREAD

**Issue by axilleas** [tutumcloud/stackfiles#66]
It would be awesome to have a link that downloads the contents of a stackfile as `docker-compose.yml`.

**Comment by MaximeHeckel** [comment]
Thanks for the idea. I'll add that to the roadmap

**Comment by MaximeHeckel** [comment]
Hey, we're adding your feature in the next release of Stackfiles that will be deployed in the next few days! I'll close this.
Hope you'll like it :)
